config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'
  post '/tvshows/:id/like' => 'tvshows#like', :as => 'like_tvshows' 
  resources :tvshows, :users


  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/tvshow.rb
# == Schema Information
#
# Table name: tvshows
#
#  id            :integer          not null, primary key
#  title         :string(255)
#  plot          :text
#  network       :string(255)
#  country       :string(255)
#  poster        :text
#  premiere_date :date
#  user_id       :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

class Tvshow < ActiveRecord::Base
	belongs_to :users
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  avatar          :text
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
	has_many :tvshows
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 before_action :authenticate

  private

  def authenticate
    @current_user = User.find_by(:id => session[:user_id])
    session[:user_id] = nil unless @current_user.present?
  end
end  

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # Login form
  def new
  end

  # Where the login form POSTs data
  def create
    @current_user = User.where(:name => params[:username]).first
    if @current_user.present? && @current_user.authenticate(params[:password])
      session[:user_id] = @current_user.id
      redirect_to root_path
    else
      @errors = 'Invalid username or password'
      render :new
      # redirect_to login_path
    # nav += "#{link_to('Sign In', login_path, :data => {:confirm => 'Are you sure?'})}"
    end
  end

  # Logout
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tvshows_controller.rb
class TvshowsController < ApplicationController

	def index
		@tvshows = Tvshow.all
	end

	def new
		redirect_to login_path unless @current_user
		@tvshow = Tvshow.new
	end

	def create
		@tvshow = Tvshow.create tvshow_params
		@current_user.tvshows << @tvshow
		redirect_to tvshows_path
	end

	def like
		@tvshow = Tvshow.find params[:id]
		@current_user.tvshows << @tvshow
		redirect_to user_path(@current_user)
	end

	def show
		@tvshow = Tvshow.find params[:id]
	end

	def edit
		@tvshow = Tvshow.find params[:id]
	end

	def update
		@tvshow = Tvshow.find params[:id]
		@tvshow.update tvshow_params
		redirect_to @tvshow
	end

	def destroy
		@tvshow = Tvshow.find params[:id]
		@tvshow.destroy
		redirect_to tvshows_path
	end

private
def tvshow_params
	params.require(:tvshow).permit(:title, :plot, :network, :country, :poster, :premiere_date)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def create
		@user = User.new user_params
		if @user.save 
			redirect_to root_path
		else
			render :new
		end
	end

	def show
		@user=User.find params[:id]
	end

	def new
		@user = User.new
	end

	def edit
    @user = @current_user
  end

  def update
  	@user = @current_user.update
  end

private
def user_params
	params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
end

end

app/helpers/application_helper.rb
# module ApplicationHelper
#   def intellinav
#     nav = ''
#     if @current_user.present?
#       nav += "<li>Hello #{ @current_user.name }</li> "
#       nav += "<li>" + link_to('All users', users_path) + "</li> "
#       nav += "<li>" + link_to('Edit profile', edit_user_path(@current_user)) + "</li> "
#       nav += "<li>#{ link_to('Sign out', login_path, :method => :delete, :data => {:confirm => 'Are you sure?'}) }</li>"
#     else
#       nav += "<li>#{ link_to('Sign up', new_user_path) }</li> "
#       nav += "<li>#{ link_to('Sign in', login_path) }</li>"
#     end
#     nav
#   end
# end

module ApplicationHelper
  def intellinav
    nav = ''
    if @current_user.present?
      nav += "<p> Welcome, #{ @current_user.name }! </p>"
       
      nav += link_to('Edit profile', edit_user_path(@current_user),:class => "signedin")
      nav += "#{ link_to('Sign out', login_path, :method => :delete, :data => {:confirm => 'Are you sure?'},:class => "signedin") }"
    else
      nav += "#{ link_to('Sign up', new_user_path,:class => "signup") }"
      nav += "#{ link_to('Sign in', login_path,:class => "signup") }"
      
    end
    nav
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title>Binger</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
  	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
	</head>

<body>
<div class="intellinav">
<%== intellinav %>
</div>

<!-- Container for Navigation Bar on left of page -->
<div class="nav">
	<div class="binger">
		<span>BINGER</span>
	</div>
	<div class="links">
		
		<p>
			<a href="<%= root_path %>"><i class="fa fa-home fa-3x"></i><br><br>MAIN MENU</a>
		</p>
		
		<p>
			<a href="<%= new_tvshow_path %>"><i class="fa fa-plus-square fa-3x"></i><br><br>ADD SHOW</a>
		</p>
		<% if @current_user.nil? %>
		<p>
			<a href="<%= new_user_path %>"><i class="fa fa-user fa-3x"></i><br><br>ADD USER</a>
	  </p>
		<% end %>
	  <p>
	  	<a href="<%= tvshows_path %>"><i class="fa fa-caret-square-o-right fa-3x"></i><br><br>ALL SHOWS</a>
		</p>
		<% if @current_user.present? %>
		<p>
			<a href="<%= user_path(@current_user) %>"><i class="fa fa-star fa-3x"></i><br><br>MY SHOWS</a>
		</p>
		<% end %>
		</div>
</div>


	<%= yield %>


</body>
</html>

app/views/pages/home.html.erb
<p class ="welcome_message">
	WELCOME TO BINGER
</p>

app/views/session/new.html.erb
<div class="user_password">

	<% if @errors %>
		<p class="error"><%= @errors %></p>
	<% end %>

<%= form_tag '/login' do %>
 
  <%= text_field_tag :username, nil, :autofocus => true, :placeholder => "Username" %>
  
  <%= password_field_tag :password %>
  <%= submit_tag 'Login' %>
<% end %>

</div>

app/views/tvshows/_form.html.erb
<%= form_for @tvshow do |f| %>
	<p>
		
		<%= f.text_field :title, :placeholder => "Title" %>
	</p>

	<p>
		
		<%= f.text_field :plot, :placeholder => "Plot" %>
	</p>

	<p>
		
		<%= f.text_field :network, :placeholder => "Network" %>
	</p>

	<p>
		
		<%= f.text_field :country, :placeholder => "Country" %>
	</p>

	<p>
		
		<%= f.text_field :poster, :placeholder => "Poster URL", :required => true %>
	</p>

	<p>
		
		<%= f.text_field :premiere_date, :placeholder => "Premiere Date" %>
	</p>
	
	<%= f.submit %>
		<% end %>

app/views/tvshows/edit.html.erb
 <div class="edit_form">

 	<%= render :partial => 'form' %>

 </div>

app/views/tvshows/index.html.erb
<div class="shows">
<% @tvshows.each do |tvshow| %>
    
    <%= link_to(image_tag(tvshow.poster, :class => 'thumbnail'), tvshow) %>
    
<% end %>
<div>

app/views/tvshows/new.html.erb
<div class="new_show_form">

<%= render :partial => 'form' %>

</div>

app/views/tvshows/show.html.erb
<div class="new_show_form">

<p><%= image_tag @tvshow.poster, :class => "poster"%></p>	
<p class ="tvshow_title"><%= @tvshow.title %></p>
<p class ="tvshow_info"><%= @tvshow.plot %></p>
<p class ="tvshow_info"><%= @tvshow.network %></p>
<p class ="tvshow_info"><%= @tvshow.country %></p>
<p class ="tvshow_info"><%= @tvshow.premiere_date %></p>

<%= link_to("Edit", edit_tvshow_path(@tvshow),:class => "edit_delete_buttons") %>
<%= link_to("Delete", tvshow_path(@tvshow), :method => 'delete',:class => "edit_delete_buttons") %>
<%= link_to("Like", like_tvshows_path(@tvshow),:method => 'post', :class => "edit_delete_buttons") %>

</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<p>
		
		<%= f.text_field :name, :placeholder => "Full Name" %>
	</p>

	<p>
		
		<%= f.text_field :email, :placeholder => "Email" %>
	</p>

	<p>
		
		<%= f.password_field :password, :placeholder => "Password" %>
	</p>

	<p>
		
		<%= f.password_field :password_confirmation, :placeholder => "Confirm Password" %>
	</p>

	<p>
		
		<%= f.text_field :avatar, :placeholder => "Avatar (URL)" %>
	</p>

	<%= f.submit %>
		<% end %>

app/views/users/edit.html.erb
<div class="user_edit_form">

<%= render :partial => 'form' %>

</div>

app/views/users/index.html.erb
<h1>Look at my seed</h1>

app/views/users/new.html.erb
<div class="new_user_form">

<%= render :partial => 'form' %>

</div>

app/views/users/show.html.erb
<div class="new_show_form fixthis">

	<h3 class="my_profile">BINGER PROFILE</h3>

	<p class="my_profile_name"><%= @user.name %></p>


</div>

<h3>MY SHOWS</h3>

<div class="shows">
	<% @user.tvshows.each do |tvshow| %>
		<%= link_to(image_tag(tvshow.poster, :class => 'thumbnail'), tvshow) %>
	<% end %>
</div>